name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: configure
    #   run: ./configure

    - name: Install dependencies
      run: ${{github.workspace}}/code/make

    - name: Run check
      run: ${{github.workspace}}/code/make check

    - name: Run distcheck
      run: ${{github.workspace}}/code/make distcheck
